[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_hardhat"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.production]
optimizer_runs = 1000000
via_ir = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

[fuzz]
runs = 256
max_test_rejects = 65536

[invariant]
runs = 256
depth = 15
fail_on_revert = true

# RPC endpoints
[rpc_endpoints]
polygon_zkevm = "${POLYGON_ZKEVM_RPC_URL}"
zksync = "${ZKSYNC_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
polygon_zkevm = { key = "${POLYGONSCAN_API_KEY}" }
zksync = { key = "${ZKSYNC_EXPLORER_API_KEY}" }

